name: build
on:
  push:
    branches: [ master ]
    tags:
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -yq \
          libboost1.67-dev \
          build-essential \
          libssl-dev \
          libfuse-dev \
    - name: Build
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=/usr/local ..
        make
        DESTDIR=install-test make install
    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: build
    - name: Release
      uses: fnkr/github-action-ghr@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GHR_COMPRESS: zip
        GHR_PATH: ./build/
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
